// ─── FIXTURE DATA ─────────────────────────────────────────
// Phase 1 only. All data comes from here.
// Phase 2: replace with real API calls — the types are identical.

import type {
  AgentVersion,
  TestCase,
  BenchmarkRun,
  RunDetail,
  RegressionReport,
  DashboardMetrics,
} from "./types";

// ── Dashboard ──────────────────────────────────────────────
export const dashboardMetrics: DashboardMetrics = {
  agent_reliability: 94.7,
  total_test_cases: 30,
  passed: 27,
  failed: 3,
  critical: 1,
  last_run_at: "2026-08-18T10:22:00Z",
  active_agents: 2,
  total_runs: 14,
};

// ── Agents ─────────────────────────────────────────────────
export const agentVersions: AgentVersion[] = [
  {
    id: "av_001",
    name: "Dispatch Agent",
    version: "v1.2",
    model: "gemini-2.0-flash",
    prompt_hash: "3f82a1",
    pass_rate: 94.7,
    total_tests: 30,
    passed: 27,
    failed: 3,
    critical_failures: 1,
    status: "active",
    created_at: "2026-08-15T08:00:00Z",
    description: "Schedules field technicians for emergency and standard service jobs using skill matching, availability checks, and SLA constraints.",
  },
  {
    id: "av_002",
    name: "Dispatch Agent",
    version: "v1.1",
    model: "gemini-2.0-flash",
    prompt_hash: "a91cd2",
    pass_rate: 97.2,
    total_tests: 30,
    passed: 29,
    failed: 1,
    critical_failures: 0,
    status: "deprecated",
    created_at: "2026-08-10T08:00:00Z",
    description: "Previous stable version. Higher pass rate but slower response times.",
  },
  {
    id: "av_003",
    name: "Dispatch Agent",
    version: "v1.0",
    model: "gemini-1.5-pro",
    prompt_hash: "b22fe9",
    pass_rate: 83.3,
    total_tests: 30,
    passed: 25,
    failed: 5,
    critical_failures: 2,
    status: "deprecated",
    created_at: "2026-08-01T08:00:00Z",
    description: "Initial prototype. Multiple critical failures on certification expiry edge cases.",
  },
];

// ── Test Cases ─────────────────────────────────────────────
export const testCases: TestCase[] = [
  {
    id: "tc_001",
    category: "dispatch",
    scenario: "Emergency AC Repair — HVAC Certified + Compressor in Stock",
    description: "Schedule emergency AC repair for tomorrow 10AM. Nearest available tech with HVAC cert and compressor part.",
    expected_outcome: "Technician with HVAC certification, available tomorrow 10AM, compressor in inventory",
    severity: "critical",
    last_result: "pass",
    last_run_at: "2026-08-18T10:22:00Z",
    tags: ["hvac", "emergency", "inventory"],
    is_mutation: false,
  },
  {
    id: "tc_002",
    category: "certification",
    scenario: "Technician Assigned with Expired Certification",
    description: "Agent must reject assignment of tech whose HVAC cert expired 30 days ago.",
    expected_outcome: "Assignment rejected — certification expired",
    severity: "critical",
    last_result: "fail",
    last_run_at: "2026-08-18T10:22:00Z",
    tags: ["certification", "expiry", "safety"],
    is_mutation: false,
  },
  {
    id: "tc_003",
    category: "availability",
    scenario: "All HVAC Technicians Unavailable",
    description: "Verify agent correctly surfaces no-available-tech error when all HVAC techs are booked.",
    expected_outcome: "No technician available — escalation triggered",
    severity: "high",
    last_result: "pass",
    last_run_at: "2026-08-18T10:22:00Z",
    tags: ["availability", "escalation"],
    is_mutation: false,
  },
  {
    id: "tc_004",
    category: "inventory",
    scenario: "Required Part Out of Stock",
    description: "Agent attempts to schedule job requiring compressor but inventory is empty.",
    expected_outcome: "Job deferred — part unavailable",
    severity: "high",
    last_result: "pass",
    last_run_at: "2026-08-18T10:22:00Z",
    tags: ["inventory", "parts", "deferral"],
    is_mutation: false,
  },
  {
    id: "tc_005",
    category: "scheduling",
    scenario: "Double Booking Detection",
    description: "Agent attempts to schedule a job that conflicts with existing appointment.",
    expected_outcome: "Conflict detected — alternative slot proposed",
    severity: "high",
    last_result: "pass",
    last_run_at: "2026-08-18T10:22:00Z",
    tags: ["scheduling", "conflict"],
    is_mutation: false,
  },
  {
    id: "tc_006",
    category: "sla",
    scenario: "SLA Breach — Emergency Job Not Dispatched in 2 Hours",
    description: "Emergency job SLA requires dispatch within 2 hours. Verify escalation triggers on breach.",
    expected_outcome: "SLA breach detected — escalated to manager",
    severity: "critical",
    last_result: "fail",
    last_run_at: "2026-08-18T10:22:00Z",
    tags: ["sla", "emergency", "escalation"],
    is_mutation: false,
  },
  {
    id: "tc_007",
    category: "dispatch",
    scenario: "Standard Plumbing Repair — Skill Match",
    description: "Standard plumbing job requiring licensed plumber with pipe repair certification.",
    expected_outcome: "Nearest available licensed plumber assigned",
    severity: "medium",
    last_result: "pass",
    last_run_at: "2026-08-18T10:22:00Z",
    tags: ["plumbing", "skill-match"],
    is_mutation: false,
  },
  {
    id: "tc_008",
    category: "dispatch",
    scenario: "Electrical Panel Upgrade — High-Voltage Cert Required",
    description: "Electrical upgrade needing high-voltage certification and specific panel kit.",
    expected_outcome: "HV-certified electrician with panel kit assigned",
    severity: "high",
    last_result: "pass",
    last_run_at: "2026-08-18T10:22:00Z",
    tags: ["electrical", "certification", "inventory"],
    is_mutation: false,
  },
  {
    id: "tc_009",
    category: "availability",
    scenario: "Outside Working Hours Request",
    description: "Request scheduled at 2AM — outside all technician working hours.",
    expected_outcome: "No availability — next-day slot proposed",
    severity: "medium",
    last_result: "pass",
    last_run_at: "2026-08-18T10:22:00Z",
    tags: ["working-hours", "scheduling"],
    is_mutation: false,
  },
  {
    id: "tc_010",
    category: "certification",
    scenario: "Invalid Technician ID in Request",
    description: "Request references non-existent technician ID tech_999.",
    expected_outcome: "Validation error — technician not found",
    severity: "high",
    last_result: "fail",
    last_run_at: "2026-08-18T10:22:00Z",
    tags: ["validation", "invalid-id"],
    is_mutation: false,
  },
  // Mutation test cases
  {
    id: "tc_011",
    category: "certification",
    scenario: "[MUTATION] HVAC Cert Expired — Should Reject",
    description: "Mutation of tc_001: HVAC certification set to expired 1 day ago.",
    expected_outcome: "Assignment rejected — certification expired",
    severity: "critical",
    last_result: "pass",
    last_run_at: "2026-08-18T10:22:00Z",
    tags: ["mutation", "certification", "expiry"],
    is_mutation: true,
    parent_id: "tc_001",
  },
  {
    id: "tc_012",
    category: "inventory",
    scenario: "[MUTATION] Compressor Qty=0 — Should Defer",
    description: "Mutation of tc_001: compressor inventory quantity set to 0.",
    expected_outcome: "Job deferred — part out of stock",
    severity: "high",
    last_result: "pass",
    last_run_at: "2026-08-18T10:22:00Z",
    tags: ["mutation", "inventory"],
    is_mutation: true,
    parent_id: "tc_001",
  },
  {
    id: "tc_013",
    category: "availability",
    scenario: "[MUTATION] Tech Marked Unavailable — Should Find Alternative",
    description: "Mutation of tc_001: primary tech marked unavailable for the requested slot.",
    expected_outcome: "Alternative technician assigned",
    severity: "medium",
    last_result: "pass",
    last_run_at: "2026-08-18T10:22:00Z",
    tags: ["mutation", "availability"],
    is_mutation: true,
    parent_id: "tc_001",
  },
];

// ── Benchmark Runs ─────────────────────────────────────────
export const benchmarkRuns: BenchmarkRun[] = [
  {
    id: "run_001",
    agent_version_id: "av_001",
    agent_name: "Dispatch Agent",
    agent_version: "v1.2",
    status: "completed",
    total_tests: 30,
    passed: 27,
    failed: 3,
    critical_failures: 1,
    pass_rate: 94.7,
    started_at: "2026-08-18T10:15:00Z",
    completed_at: "2026-08-18T10:22:00Z",
    duration_ms: 420000,
    mutation_testing: true,
    compare_against: "v1.1",
    triggered_by: "manual",
  },
  {
    id: "run_002",
    agent_version_id: "av_002",
    agent_name: "Dispatch Agent",
    agent_version: "v1.1",
    status: "completed",
    total_tests: 30,
    passed: 29,
    failed: 1,
    critical_failures: 0,
    pass_rate: 97.2,
    started_at: "2026-08-15T09:00:00Z",
    completed_at: "2026-08-15T09:07:00Z",
    duration_ms: 420000,
    mutation_testing: false,
    triggered_by: "manual",
  },
  {
    id: "run_003",
    agent_version_id: "av_003",
    agent_name: "Dispatch Agent",
    agent_version: "v1.0",
    status: "completed",
    total_tests: 30,
    passed: 25,
    failed: 5,
    critical_failures: 2,
    pass_rate: 83.3,
    started_at: "2026-08-10T11:00:00Z",
    completed_at: "2026-08-10T11:08:00Z",
    duration_ms: 480000,
    mutation_testing: false,
    triggered_by: "manual",
  },
];

// ── Run Detail ─────────────────────────────────────────────
export const runDetails: Record<string, RunDetail> = {
  run_001: {
    ...benchmarkRuns[0],
    test_case: testCases[0],
    agent_request:
      "Schedule an emergency AC repair tomorrow at 10 AM. Find the nearest available technician who has the required HVAC certification and compressor.",
    agent_decision: {
      technician_id: "tech_007",
      scheduled_at: "2026-08-19T10:00:00Z",
      reason:
        "Tech #007 (Maria Chen) is the nearest available HVAC-certified technician with compressor in inventory. Distance: 4.2km. Cert valid until 2027-03-15.",
    },
    latency_ms: 2340,
    steps: [
      {
        id: "step_001",
        step_index: 0,
        type: "intent_parsing",
        name: "INTENT PARSING",
        input: { raw_request: "Schedule emergency AC repair tomorrow 10AM..." },
        output: {
          intent: "schedule_job",
          job_type: "AC_REPAIR",
          urgency: "emergency",
          requested_time: "2026-08-19T10:00:00Z",
          required_skills: ["HVAC_CERT"],
          required_parts: ["COMPRESSOR_R22"],
        },
        status: "pass",
        latency_ms: 420,
      },
      {
        id: "step_002",
        step_index: 1,
        type: "tool_call",
        name: "find_available_technicians()",
        input: {
          skill: "HVAC_CERT",
          requested_at: "2026-08-19T10:00:00Z",
          location: { lat: 12.9716, lng: 77.5946 },
        },
        output: {
          technicians: [
            { id: "tech_007", name: "Maria Chen", distance_km: 4.2 },
            { id: "tech_012", name: "Rajan Patel", distance_km: 7.8 },
          ],
        },
        status: "pass",
        latency_ms: 180,
      },
      {
        id: "step_003",
        step_index: 2,
        type: "tool_call",
        name: "check_skills(tech_007)",
        input: { technician_id: "tech_007", required_skills: ["HVAC_CERT"] },
        output: {
          certified: true,
          cert_expiry: "2027-03-15",
          skills: ["HVAC_CERT", "ELECTRICAL_BASIC"],
        },
        status: "pass",
        latency_ms: 95,
      },
      {
        id: "step_004",
        step_index: 3,
        type: "tool_call",
        name: "check_inventory(tech_007)",
        input: { technician_id: "tech_007", parts: ["COMPRESSOR_R22"] },
        output: { available: true, quantity: 2, part_id: "COMPRESSOR_R22" },
        status: "pass",
        latency_ms: 110,
      },
      {
        id: "step_005",
        step_index: 4,
        type: "tool_call",
        name: "check_schedule(tech_007)",
        input: {
          technician_id: "tech_007",
          requested_at: "2026-08-19T10:00:00Z",
          duration_hours: 2,
        },
        output: { available: true, next_slot: "2026-08-19T10:00:00Z" },
        status: "pass",
        latency_ms: 88,
      },
      {
        id: "step_006",
        step_index: 5,
        type: "tool_call",
        name: "check_sla()",
        input: { job_type: "emergency", urgency: "emergency" },
        output: {
          sla_hours: 4,
          deadline: "2026-08-19T14:00:00Z",
          within_sla: true,
        },
        status: "pass",
        latency_ms: 72,
      },
      {
        id: "step_007",
        step_index: 6,
        type: "decision",
        name: "AGENT DECISION",
        output: {
          technician_id: "tech_007",
          scheduled_at: "2026-08-19T10:00:00Z",
          reason: "All checks passed. Tech #007 assigned.",
        },
        status: "pass",
        latency_ms: 1280,
      },
      {
        id: "step_008",
        step_index: 7,
        type: "evaluation",
        name: "DETERMINISTIC VALIDATION",
        output: { passed: true, checks: 9, failures: 0 },
        status: "pass",
        latency_ms: 15,
      },
    ],
    evaluation: [
      {
        rule: "technician_exists",
        passed: true,
        severity: "critical",
        expected: "tech_007 exists in database",
        actual: "tech_007 found",
        reason: "Technician record found in PostgreSQL",
      },
      {
        rule: "technician_available",
        passed: true,
        severity: "high",
        expected: "Available at 2026-08-19T10:00:00Z",
        actual: "Available",
        reason: "No conflicting appointments",
      },
      {
        rule: "required_certification",
        passed: true,
        severity: "critical",
        expected: "HVAC_CERT present",
        actual: "HVAC_CERT present, expires 2027-03-15",
        reason: "Certification valid and not expired",
      },
      {
        rule: "certification_expiry",
        passed: true,
        severity: "critical",
        expected: "Cert expiry > today",
        actual: "Expires 2027-03-15 (>200 days remaining)",
        reason: "Certification current",
      },
      {
        rule: "required_part",
        passed: true,
        severity: "high",
        expected: "COMPRESSOR_R22 in inventory",
        actual: "Qty: 2",
        reason: "Part in stock",
      },
      {
        rule: "sla_compliance",
        passed: true,
        severity: "critical",
        expected: "Dispatch within 4 hours",
        actual: "Scheduled within 24h window per emergency SLA",
        reason: "SLA met",
      },
    ],
  },
};

// ── Regression ─────────────────────────────────────────────
export const regressionReport: RegressionReport = {
  id: "reg_001",
  agent_name: "Dispatch Agent",
  baseline_version: "v1.1",
  current_version: "v1.2",
  baseline_pass_rate: 97.2,
  current_pass_rate: 94.7,
  delta: -2.5,
  regression_detected: true,
  new_failures: [testCases[1], testCases[5]],
  fixed_tests: [],
  critical_regressions: 1,
  created_at: "2026-08-18T10:22:00Z",
};
